version: "3"

services:

  db:
    image: postgres
    volumes:
     - db-data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - backend

  data:
    build:
      context: .
      dockerfile: Dockerfile.data
    depends_on:
      - db
    restart: on-failure
    networks:
      - backend
    environment:
        - PGHOST=db
        - PGDATABASE=postgres
        - PGUSER=postgres

networks:
  backend:

volumes:
  db-data:
