# use an official python runtime as parent image
FROM python

# copy needed directories into container
ADD . /

# install python requirements
WORKDIR /scripts
RUN pip install -e .

# ingest data
ENTRYPOINT ["python", "create-tables.py"]
CMD ["db"]
